[package]
name = "quarkpad"
version = "2.2.2"
edition = "2024"
description = "A simple game launcher for Linux to manage and launch games using Proton."
authors = ["Asadul Al Galib <asadulgalibvat69@gmail.com>"]
license = "Unlicense"
repository = "https://github.com/galib45/quarkpad"

[dependencies]
adw = { version = "0.9.1", package = "libadwaita", features = ["v1_8"] }
chrono = { version = "0.4.44", features = ["serde"] }
dirs = "6.0.0"
gtk = { version = "0.11.1", package = "gtk4", features = ["blueprint", "v4_20"] }
serde = { version = "1.0.228", features = ["derive"] }
smol = "2.0.2"
strip-ansi-escapes = "0.2.1"
toml = "1.1.0"

[build-dependencies]
glib-build-tools = "0.22.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
