[package]
name = "quarkpad"
version = "2.1.0"
edition = "2024"
description = "A simple game launcher for Linux to manage and launch games using Proton."
authors = ["Asadul Al Galib <asadulgalibvat69@gmail.com>"]
license = "Unlicense"
repository = "https://github.com/galib45/quarkpad"

[dependencies]
adw = { version = "0.8.1", package = "libadwaita", features = ["v1_8"] }
chrono = "0.4.43"
dirs = "6.0.0"
gtk = { version = "0.10.3", package = "gtk4", features = ["blueprint", "v4_20"] }
# rfd = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
smol = "2.0.2"
strip-ansi-escapes = "0.2.1"
toml = "0.9.11"

[build-dependencies]
glib-build-tools = "0.21.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
