import { Button, ScrollView, TextEdit, Palette } from "std-widgets.slint";
import { Settings, SettingsPage } from "settings.slint";
import { HomePage } from "home.slint";
import { AddGamePage, Game } from "add-game.slint";
import { ThemeAgnosticColors } from "colors.slint";

component LogsDialog inherits Dialog {
    in-out property <string> content <=> text-edit.text;
    callback close-clicked <=> close-button.clicked;
    width: 600px;
    height: 400px;
    Rectangle {
        background: Palette.alternate-background;
        VerticalLayout {
            width: parent.width - 16px;
            padding: 8px;
            spacing: 16px;
            Text {
                text: "Logs";
                font-size: 16px;
            }

            text-edit := TextEdit {
                read-only: true;
            }

            HorizontalLayout {
                padding-top: 8px;
                spacing: 16px;
                alignment: end;
                scroll-button := Button {
                    text: "Scroll";
                    width: 128px;
                    clicked => {
                        text-edit.viewport-y = min(0px, - text-edit.viewport-height + text-edit.visible-height);
                    }
                }

                close-button := Button {
                    text: "Close";
                    primary: true;
                    width: 128px;
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    in-out property <int> current_page: 0;
    in-out property <Settings> settings;
    in-out property <Game> game;
    in property <[Game]> games: [
        {
            name: "Hollow Knight",
            cover-path: "/home/galib/Downloads/hollow-knight.jpg",
            exe-path: "/mnt/data/games/installed/Hollow Knight v1.5.78.11833/Hollow Knight.exe",
            wineprefix: "/mnt/data/games/wineprefix"
        },
        {
            name: "Need for Speed: Most Wanted (2012)",
            cover-path: "/home/galib/Downloads/Nfs-most-wanted-2012-gen-packart.jpg",
            exe-path: "/mnt/data/games/installed/Need for Speed - Most Wanted/NFS13.exe",
            wineprefix: "/mnt/data/games/wineprefix"
        },
        {
            name: "FIFA 16",
            cover-path: "/home/galib/Downloads/fifa16.jpg",
            exe-path: "/mnt/data/games/installed/FIFA 16/fifa16.exe",
            wineprefix: "/mnt/data/games/wineprefix"
        },
        {
            name: "Half-Life",
            cover-path: "/home/galib/Downloads/half-life.jpg",
            exe-path: "/mnt/data/games/installed/Half-Life/hl.exe",
            wineprefix: "/mnt/data/games/wineprefix"
        }
    ];
    in property <int> editing: -1;
    in property <bool> show-logs-dialog: false;
    in property <string> logs-content;

    // home callbacks
    callback settings-clicked();
    callback add-fab-clicked();
    pure callback load-image(string) -> image;
    callback remove-game(int);
    callback edit-game(int);
    callback launch-game(int);
    callback winecfg(int);

    // settings callbacks
    callback choose-proton-path();
    callback choose-umu-path();
    callback click-save-settings();
    callback back-clicked();

    // add-game callbacks
    callback choose-cover-path();
    callback choose-exe-path();
    callback choose-wineprefix();
    callback click-save-game();
    callback cover-path-edited();
    callback exe-path-edited();
    callback wineprefix-edited();
    callback toggle-gamescope();
    callback gamescope-width-edited();
    callback gamescope-height-edited();

    callback logs-dialog-close-clicked();

    // preferred-width: 800px;
    // preferred-height: 600px;
    title: "Quarkpad";

    if current_page == 0: home-page := HomePage {
        games: games;
        load-image(path) => {
            load-image(path)
        }
        remove-game(index) => {
            remove-game(index)
        }
        edit-game(index) => {
            edit-game(index)
        }
        launch-game(index) => {
            launch-game(index)
        }
        winecfg(index) => {
            winecfg(index)
        }
        settings-clicked => {
            settings-clicked()
        }
        add-fab-clicked => {
            add-fab-clicked()
        }
    }

    if current_page == 1: SettingsPage {
        settings: settings;
        choose-proton-path => {
            choose-proton-path()
        }
        choose-umu-path => {
            choose-umu-path()
        }
        click-save => {
            click-save-settings()
        }
        back-clicked => {
            back-clicked()
        }
    }

    if current_page == 2: AddGamePage {
        back-clicked => {
            back-clicked()
        }
        game: game;
        choose-cover-path => {
            choose-cover-path()
        }
        choose-exe-path => {
            choose-exe-path()
        }
        choose-wineprefix => {
            choose-wineprefix()
        }
        click-save => {
            click-save-game()
        }
        name-edited(text) => {
            game.name = text
        }
        cover-path-edited(text) => {
            game.cover-path = text
        }
        exe-path-edited(text) => {
            game.exe-path = text
        }
        wineprefix-edited(text) => {
            game.wineprefix = text
        }
        toggle-gamescope() => {
            game.use-gamescope = !game.use-gamescope
        }
        gamescope-width-edited(text) => {
            game.gamescope-width = text.to-float()
        }
        gamescope-height-edited(text) => {
            game.gamescope-height = text.to-float()
        }
    }

    if show-logs-dialog: LogsDialog {
        content: logs-content;
        close-clicked => {
            logs-dialog-close-clicked()
        }
    }
}
