import { Button, ScrollView } from "std-widgets.slint";
import { Settings, SettingsPage } from "settings.slint";
import { HomePage } from "home.slint";
import { AddGamePage, Game } from "add-game.slint";

export component App inherits Window {
    in-out property <int> current_page: 0;
    in-out property <Settings> settings;
    in-out property <Game> game;
    in property <[Game]> games: [
        {
            name: "Hollow Knight",
            cover-path: "/home/galib/Downloads/hollow-knight.jpg",
            exe-path: "/mnt/data/games/installed/Hollow Knight v1.5.78.11833/Hollow Knight.exe",
            wineprefix: "/mnt/data/games/wineprefix"
        },
        {
            name: "Need for Speed: Most Wanted (2012)",
            cover-path: "/home/galib/Downloads/Nfs-most-wanted-2012-gen-packart.jpg",
            exe-path: "/mnt/data/games/installed/Need for Speed - Most Wanted/NFS13.exe",
            wineprefix: "/mnt/data/games/wineprefix"
        },
        {
            name: "FIFA 16",
            cover-path: "/home/galib/Downloads/fifa16.jpg",
            exe-path: "/mnt/data/games/installed/FIFA 16/fifa16.exe",
            wineprefix: "/mnt/data/games/wineprefix"
        },
        {
            name: "Half-Life",
            cover-path: "/home/galib/Downloads/half-life.jpg",
            exe-path: "/mnt/data/games/installed/Half-Life/hl.exe",
            wineprefix: "/mnt/data/games/wineprefix"
        }
    ];
    in property <int> editing: -1;

    // home callbacks
    callback settings-clicked();
    callback add-fab-clicked();
    pure callback load-image(string) -> image;
    callback remove-game(int);
    callback edit-game(int);
    callback launch-game(int);
    callback winecfg(int);

    // settings callbacks
    callback choose-proton-path();
    callback choose-umu-path();
    callback click-save-settings();
    callback back-clicked();

    // add-game callbacks
    callback choose-cover-path();
    callback choose-exe-path();
    callback choose-wineprefix();
    callback click-save-game();
    callback cover-path-edited();
    callback exe-path-edited();
    callback wineprefix-edited();
    callback toggle-gamescope();
    callback gamescope-width-edited();
    callback gamescope-height-edited();

    // preferred-width: 800px;
    // preferred-height: 600px;
    title: "Quarkpad";

    if current_page == 0: home-page := HomePage {
        games: games;
        load-image(path) => {
            load-image(path)
        }
        remove-game(index) => {
            remove-game(index)
        }
        edit-game(index) => {
            edit-game(index)
        }
        launch-game(index) => {
            launch-game(index)
        }
        winecfg(index) => {
            winecfg(index)
        }
        settings-clicked => {
            settings-clicked()
        }
        add-fab-clicked => {
            add-fab-clicked()
        }
    }

    if current_page == 1: SettingsPage {
        settings: settings;
        choose-proton-path => {
            choose-proton-path()
        }
        choose-umu-path => {
            choose-umu-path()
        }
        click-save => {
            click-save-settings()
        }
        back-clicked => {
            back-clicked()
        }
    }

    if current_page == 2: AddGamePage {
        back-clicked => {
            back-clicked()
        }
        game: game;
        choose-cover-path => {
            choose-cover-path()
        }
        choose-exe-path => {
            choose-exe-path()
        }
        choose-wineprefix => {
            choose-wineprefix()
        }
        click-save => {
            click-save-game()
        }
        name-edited(text) => {
            game.name = text
        }
        cover-path-edited(text) => {
            game.cover-path = text
        }
        exe-path-edited(text) => {
            game.exe-path = text
        }
        wineprefix-edited(text) => {
            game.wineprefix = text
        }
        toggle-gamescope() => {
            game.use-gamescope = !game.use-gamescope
        }
        gamescope-width-edited(text) => {
            game.gamescope-width = text.to-float()
        }
        gamescope-height-edited(text) => {
            game.gamescope-height = text.to-float()
        }
    }
}
