import { AppBar, CompositeButton } from "components.slint";
import {
    ScrollView,
    Button,
    ListView,
    VerticalBox,
    Palette,
} from "std-widgets.slint";
import { Game } from "add-game.slint";
import { ThemeAgnosticColors } from "colors.slint";

component GameCard inherits Rectangle {
    in property <image> cover;

    border-width: 2px;
    border-color: gray;
    border-radius: 12px;
    clip: true;

    Image {
        source: cover;
        image-fit: fill;
        width: parent.width;
        height: parent.height;
    }
}

component PopupMenuButton {
    in property <string> text;
    in property <image> icon;
    in property <color> tint: Palette.foreground;
    callback clicked <=> cb.clicked;
    cb := CompositeButton {
        tint: tint;
        HorizontalLayout {
            padding-top: 8px;
            padding-bottom: 8px;
            padding-left: 16px;
            padding-right: 16px;
            spacing: 16px;
            alignment: start;

            if icon.height != 0: Image {
                source: icon;
                colorize: tint;
                height: 20px;
            }

            if !text.is-empty: Text {
                text: text;
                vertical-alignment: center;
                color: tint;
            }
        }
    }
}

export component HomePage inherits Rectangle {
    in property <[Game]> games;
    callback settings-clicked <=> app_bar.icon-clicked;
    callback add-fab-clicked <=> add-fab.clicked;
    pure callback load-image(string) -> image;
    callback remove-game(int);
    callback edit-game(int);
    callback launch-game(int);
    callback winecfg(int);

    VerticalLayout {
        app-bar := AppBar {
            title: "Games";
            trailing-icon: @image-url("../resources/settings.svg");
        }

        ScrollView {
            HorizontalLayout {
                alignment: center;
                padding: 32px;

                VerticalLayout {
                    spacing: 32px;
                    for game[i] in games: HorizontalLayout {
                        spacing: 16px;
                        GameCard {
                            cover: load-image(game.cover-path);
                            width: 120px;
                            height: 150px;
                        }

                        HorizontalLayout {
                            width: 400px;
                            padding-top: 8px;
                            spacing: 32px;
                            Text {
                                text: game.name;
                                font-size: 20px;
                                wrap: word-wrap;
                            }

                            VerticalLayout {
                                Button {
                                    icon: @image-url("../resources/more_vert.svg");
                                    icon-size: 24px;
                                    colorize-icon: true;
                                    height: 32px;
                                    width: 48px;
                                    clicked => {
                                        popup.show()
                                    }
                                }

                                popup := PopupWindow {
                                    y: 36px;
                                    Rectangle {
                                        background: Palette.control-background;
                                        VerticalLayout {
                                            PopupMenuButton {
                                                icon: @image-url("../resources/rocket_launch.svg");
                                                text: "Launch";
                                                clicked => {
                                                    launch-game(i);
                                                }
                                            }

                                            PopupMenuButton {
                                                icon: @image-url("../resources/edit.svg");
                                                text: "Edit";
                                                clicked => {
                                                    edit-game(i);
                                                }
                                            }

                                            PopupMenuButton {
                                                icon: @image-url("../resources/delete.svg");
                                                text: "Remove";
                                                tint: ThemeAgnosticColors.red;
                                                clicked => {
                                                    remove-game(i);
                                                }
                                            }

                                            PopupMenuButton {
                                                icon: @image-url("../resources/wine_logo.svg");
                                                text: "Run winecfg";
                                                clicked => {
                                                    winecfg(i);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    add-fab := Button {
        icon: @image-url("../resources/add_2.svg");
        text: "Add Game";
        colorize-icon: true;
        x: parent.width - self.width - 16px;
        y: parent.height - self.height - 16px;
    }
}
