import { LineEdit, Button, ScrollView } from "std-widgets.slint";
import { FileInput, AppBar, FileInputWithLabel } from "components.slint";

export struct Settings {
    proton_path: string,
    umu_path: string,
}

export component SettingsPage inherits Rectangle {
    in-out property <Settings> settings;
    callback back-clicked <=> app-bar.icon-clicked;
    callback choose-proton-path <=> proton-path-input.choose-file;
    callback choose-umu-path <=> umu-path-input.choose-file;
    callback click-save <=> save-button.clicked;

    VerticalLayout {
        app-bar := AppBar {
            title: "Settings";
            trailing-icon: @image-url("../resources/arrow_back_ios.svg");
        }

        ScrollView {
            HorizontalLayout {
                padding: 32px;
                width: min(600px, max(300px, parent.width * 0.8));
                VerticalLayout {
                    padding: 16px;
                    spacing: 16px;
                    alignment: start;

                    proton-path-input := FileInputWithLabel {
                        label: "Proton Path";
                        text: settings.proton-path;
                        folder: true;
                    }

                    umu-path-input := FileInputWithLabel {
                        label: "Umu Path";
                        text: settings.umu-path;
                        folder: true;
                    }

                    HorizontalLayout {
                        padding-top: 64px;
                        alignment: center;

                        save-button := Button {
                            text: "Save";
                            width: 128px;
                            height: 32px;
                            primary: true;
                        }
                    }
                }
            }
        }
    }
}
